version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - blog-network

  mysql:
    container_name: mysql-blog
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=testsql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - blog-network

volumes:
  mysql-volume:

networks:
  blog-network:
    name: blog-network
    external: true