apiVersion: v1
kind: Service
metadata:
  namespace: blog
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql

spec:
  ports:
  - name: mysql 
    port: 3306
  clusterIP: None
  selector:
    app: mysql


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: mysql-read
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306


