apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-blog
  rules:
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-blog
            port:
              number: 3000
