apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    deploymet: blog
  namespace: blog
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 120
  replicas: 2
  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      labels:
        app: blog
    
    spec:
      containers:
      - name: app  
        image: blog:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /aboutme
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30

