apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    deploymet: blog
  namespace: {{ .Values.namespace }}
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 120
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      labels:
        app: blog
    
    spec:
      containers:
      - name: app  
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.version }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.deployment.ports.containerPort }}

        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.deployment.ports.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /aboutme
            port: {{ .Values.deployment.ports.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 30

