name: Blog deployment
run-name: blog deployment

on:
  push:
    branches: main
  
jobs:
  setup-environment:
      runs-on: blog 
      steps:
        -
          name: checkout source
          uses: actions/checkout@v3

        -
          name: image buildx setup
          uses: docker/setup-buildx-action@v1
        
        # -
          # name: login to docker
          # uses: docker/login-action@v2
          # with:
          #   username: ${{ docker.username }}
          #   password: ${{ docker.password }}

        -
          name: bring down the current deployment using docker-compose plugin
          run: docker compose down

        -
          name: remove the old image
          run: docker rmi blog-app
      
  build-image:
    needs: setup-environment
    runs-on: blog
    steps:
        -
          name: build image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: blog-app:latest

  deploy-image:
    needs: build-image
    runs-on: blog
    steps:
        -
          name: deploy using docker-compose plugin
          if: always()
          run: docker compose up -d
