name: Blog deployment
run-name: blog deployment

on:
  push:
    branches: [dev, main]
  
jobs:
  runs-on:
    - self-hosted
    - blog
  
  steps:
    -
      name: checkout source
      uses: actions/checkout@v3

    -
      name: build image with latest tag
      uses: docker/setup-buildx-action@v1
    
    # -
      # name: login to docker
      # uses: docker/login-action@v2
      # with:
      #   username: ${{ docker.username }}
      #   password: ${{ docker.password }}

    -
      name: remove the old image
      run: docker rmi blog-app
  
    -
      name: build image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: blog-app:latest

    -
      name: deploy using docker-compose plugin
      if: always()
      run: docker compose up -d
