name: Blog local
run-name: Localhost Deployment

on:
    push: 
        branches: [local-dev]

jobs:
    fetch-build:
        runs-on: home
        steps:
            - 
                name: fetch code
                uses: actions/checkout@v3
            
            -
                name: setup docker environment
                uses: docker/setup-buildx-action@v3
            
            -
                name: configure env variables
                run: |
                    ls -a ;
                    pwd ;
                    sed -i 's/API_PORT=/API_PORT=${{ secrets.API_PORT }}/g' .env
                    export Imagetag="blog-app:${GITHUB_SHA}"
                    echo $Imagetag

            # -
                # name: login to docker hub
                # uses: docker/login-action@v3
                # with:
                #     username: ${{ secrets.Registry_Username }}
                #     password: ${{ secrets.Registry_Password }}
            -
                name: build docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    push: false
                    tags: sinabehmanesh/blog:latest,blog-app:latest
            
            -
                name: helm package
                run: |
                    helm lint blog-chart

            -
                name: helm package and push
                run: |
                    helm package blog-chart
                    helm push blog-chart-* oci://registry-1.docker.io/sinabehmanesh || true

    terraform-deploy:
        runs-on: home
        needs: fetch-build
        defaults:
            run:
                working-directory: "terraform"
        steps:
            # -
            #     name: login to docker hub
            #     uses: docker/login-action@v3
            #     with:
            #         username: ${{ secrets.Registry_Username }}
            #         password: ${{ secrets.Registry_Password }}

            -
                name: fetch code
                uses: actions/checkout@v3

            -
                name: configure env variables
                run: |
                    ls -a ;
                    pwd ;
                    cat <<EOT >> variables.tf
                    variable "config_path" {
                        description = "address to the kubectl config file"
                        type = string
                        default = "${{ secrets.LOCAL_CLUSTER_KUBE_CONFIG }}"
                    }
                    EOT
                    cat variables.tf
            -
                name: apply terraform and auto approve
                run: |
                    terraform init
                    terraform validate
                    terraform plan
                    terraform apply -auto-approve

            

#Using terraform to deploy helm charts.

    # helm-package:
    #     runs-on: home
    #     steps:
    #         -
    #             name: package helm chart

    #         -
    #             name: perform 


    # deploy-image:
    #     runs-on: [localhost, home]
    #     steps:
    #         -
    #             name: upgrade helm
    #             run: |
    #                 helm upgrade blog ./blog-chart
               
    #         -
    #             name: check deployment status
    #             uses: 
             
    #         -
    #             name: notify me
    #             run: |