name: Blog local
run-name: Localhost Deployment
    
on:
    push: 
        branches: [kube-migration]

jobs:
    fetch-build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: fetch code
                uses: actions/checkout@v3
            
            -
                name: setup docker environment
                uses: docker/setup-buildx-action@v1
            
            -
                name: configure env variables
                run: |
                    ls -a ;
                    pwd ;
                    export Imagetag="blog-app:${GITHUB_SHA}"
                    echo $Imagetag

            -
                name: login to docker hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.Registry_Username }}
                    password: ${{ secrets.Registry_Password }}
            -
                name: build docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: sinabehmanesh/blog:latest,${{ secrets.REGISTRY_USERNAME }}/blog:${{ env.Imagetag }}

    # helm-package:
    #     runs-on: home
    #     steps:
    #         -
    #             name: package helm chart

    #         -
    #             name: perform 


    # deploy-image:
    #     runs-on: [localhost, home]
    #     steps:
    #         -
    #             name: upgrade helm
    #             run: |
    #                 helm upgrade blog ./blog-chart
               
    #         -
    #             name: check deployment status
    #             uses: 
             
    #         -
    #             name: notify me
    #             run: |