name: Blog local
run-name: Localhost Deployment
    
on:
    push: 
        branches: [kube-migration]

env:
    ImageSHA: 

jobs:
    fetch-build:
        runs-on: home
        steps:
            - 
                name: fetch code
                uses: actions/checkout@v3
            
            -
                name: setup docker environment
                uses: docker/setup-buildx-action@v1
            
            -
                name: configure env variables
                run: |
                    ls -a ;
                    pwd ;
                    echo "blog-app:${GITHUB_SHA}"
                    export Imagetag="blog-app:${GITHUB_SHA}"
                
            -
                name: build docker image
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./Dockerfile
                    push: false
                    tags: blog-app:${Imagetag}

    # helm-package:
    #     runs-on: home
    #     steps:
    #         -
    #             name: package helm chart

    #         -
    #             name: perform 


    # deploy-image:
    #     runs-on: [localhost, home]
    #     steps:
    #         -
    #             name: upgrade helm
    #             run: |
    #                 helm upgrade blog ./blog-chart
               
    #         -
    #             name: check deployment status
    #             uses: 
             
    #         -
    #             name: notify me
    #             run: |