name: Blog deployment
run-name: blog deployment

on:
  push:
    branches:
      - "main"
      - 'dev'

  pull_request:
    branches:
      - "*"

jobs:
  Code-quality-check:
    runs-on: ubuntu-latest
    steps:
        - name: checkout source
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: Install golangci-lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

        - name: Run golangci-lint
          run: golangci-lint run --timeout=5m
  
  Build-image:
    runs-on: ubuntu-latest
    steps:
        -
          name: checkout source
          uses: actions/checkout@v3
        -
          name: create .env file
          run: touch .env || true
        -
          name: build image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: blog-app:latest

  Deploy-image:
    needs: Build-image
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
        -
          name: deploy using docker-compose plugin
          if: always()
          run: docker compose up -d
