name: Blog deployment
run-name: blog deployment

on:
  push:
    branches:
      - "main"
      - 'dev'

  pull_request:
    branches:
      - "*"

jobs:
  Code-quality-check:
    runs-on: ubuntu-latest
    steps:
        -
          name: checkout source
          uses: actions/checkout@v2.4.0
        -
          name: install linters
          run: |
              snap install golangci-lint
        -
          name: lint Golang
          run: |
              pwd
              ls
  Build-image:
    runs-on: ubuntu-latest
    steps:
        -
          name: checkout source
          uses: actions/checkout@v2.4.0
        -
          name: create .env file
          run: touch .env || true
        -
          name: build image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: blog-app:latest

  Deploy-image:
    needs: Build-image
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
        -
          name: deploy using docker-compose plugin
          if: always()
          run: docker compose up -d
