name: Blog deployment
run-name: blog deployment

on:
  push:
    branches: [main]
  
jobs:
  Configure-environment:
      runs-on: blog 
      steps:
        -
          name: checkout source
          uses: actions/checkout@v3

        -
          name: image buildx setup
          uses: docker/setup-buildx-action@v1
        
        -
          name: Configure .env file
          run: |
            ls -a ;
            pwd ;
            sed -i 's/DB_USERNAME=/DB_USERNAME=${{ secrets.PROD_DB_USERNAME }}/g' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}/g' .env
            sed -i 's/DB_HOST=/DB_HOST=${{ secrets.PROD_DB_HOST }}/g' .env
            sed -i 's/DB_PORT=/DB_PORT=${{ secrets.PROD_DB_PORT }}/g' .env
        # -
          # name: login to docker
          # uses: docker/login-action@v2
          # with:
          #   username: ${{ docker.username }}
          #   password: ${{ docker.password }}

        -
          name: bring down the current deployment using docker-compose plugin
          run: docker compose down
      
  Build-image:
    needs: Configure-environment
    runs-on: blog
    steps:
        -
          name: build image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: blog-app:latest

  Deploy-image:
    needs: Build-image
    runs-on: blog
    steps:
        -
          name: deploy using docker-compose plugin
          if: always()
          run: docker compose up -d
