name: Blog deployment
run-name: blog deployment

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  
jobs:
  Configure-environment:
      runs-on: blog 
      steps:
        -
          name: checkout source
          uses: actions/checkout@v3

        -
          name: image buildx setup
          uses: docker/setup-buildx-action@v1
        -
          name: create .env file
          run: touch .env || true
        -
          name: bring down the current deployment using docker-compose plugin
          run: docker compose down
      
  Build-image:
    needs: Configure-environment
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: blog
    steps:
        -
          name: build image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: blog-app:latest

  Deploy-image:
    needs: Build-image
    runs-on: blog
    steps:
        -
          name: deploy using docker-compose plugin
          if: always()
          run: docker compose up -d
